[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
fast_qr = { version = "0.12.7", features = ["image", "svg"] }
regex = "1.11.1"
wasm-bindgen = "0.2.78"
